---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.ServiceName}}
  namespace: {{.Values.NameSpace}}
spec:
  ports:
  - port: {{.Values.ServicePort}}
    protocol: {{.Values.Protocol}}
    targetPort: {{.Values.ServiceTargatePort}}
  selector:
    name: {{.Values.LabelName}}
  